INSERT INTO "APP.PAIS"
	  VALUES (1,'PORTUGAL','URL BANDEIRA PT');
INSERT INTO "APP.PAIS"
	  VALUES (2,'ESPANHA','URL BANDEIRA ES');
INSERT INTO "APP.PAIS"
	  VALUES (3,'INGLATERRA','URL BANDEIRA ES');
	  
INSERT INTO "APP.MOEDA"
	  VALUES (1,'EURO');
INSERT INTO "APP.MOEDA"
	  VALUES (2,'LIBRA');
INSERT INTO "APP.MOEDA"
	  VALUES (3,'DOLAR');	  
	  
INSERT INTO "APP.LINGUA"
	  VALUES (1,'PORTUGUES');
INSERT INTO "APP.LINGUA"
	  VALUES (2,'ESPANHOL');
INSERT INTO "APP.LINGUA"
	  VALUES (3,'INGLES');	
	 
INSERT INTO "APP.CONTINENTE"
	  VALUES (1,'EUROPA','Continente EUROPEU');
INSERT INTO "APP.CONTINENTE"
	  VALUES (2,'AMERICA','Continente AMERICANO');
	  
INSERT INTO "APP.COORDENADAS"
	  VALUES (1,'1','1','1');
INSERT INTO "APP.COORDENADAS"
	  VALUES (2,'2','2','2');
INSERT INTO "APP.COORDENADAS"
	  VALUES (3,'3','3','3');  
	  
INSERT INTO "APP.ESTADO"
	  VALUES (1,'OK');
INSERT INTO "APP.ESTADO"
	  VALUES (2,'KO');

INSERT INTO "APP.CIDADE"
      VALUES (1, 'Porto', 'Cidade do Porto', '300KM','10000',1,1,1,1,'URL BANDEIRA PORTO',1,1);
	  
INSERT INTO "APP.CIDADE"
      VALUES (2, 'Lisboa', 'Cidade de Lisboa', '600KM','20000',1,1,1,1,'URL BANDEIRA LISBOA',2,1);

INSERT INTO "APP.CIDADE"
      VALUES (3, 'Madrid', 'Cidade de Madrid', '10000KM','30000',2,2,2,1,'URL BANDEIRA MADRID',3,1);